### ISSUE TITLE
Just some questions

### ISSUE THREAD

**Issue by TheLastProject** [ziadOUA/zCard#1]
Hey @ziadOUA,

I stumbled upon your fork randomly and I just have some questions. I hope you don't mind me doing this in a GitHub issue as I wasn't able to find an email address for you :)

1. Is there any reason you haven't made any merge requests on the Catima GitHub to submit your changes to me? I'm not a designer and I would love to have more design help in Catima and I wonder if there is any specific reason you made such a hard fork. Working together is nicer than forking in my view and I would love to know if there is anything I can do to make it easier to contribute to Catima so all the existing users can get UI improvements :)

2. Why did you not use the "Fork" button in GitHub? Catima has 7 years of history containing many changes by different authors. The git commit history allows people to see who made what change so all contributors are properly credited for their work. By reuploading the full Catima codebase under your own name in a single commit it looks like you wrote all the code yourself which can feel hurtful for all the people who worked on it as their work is made invisible in your fork. Using the fork button would've also made it much easier to keep up-to-date with changes in Catima and contribute back without getting hard to resolve merge conflicts.

Thanks :)

**Comment by ziadOUA** [comment]
Hello @TheLastProject !

Thanks for these very pertinent questions.

First, I am neither an experienced programmer nor an experienced designer : I'm very new to android development, versioning, Git, and my designing "skills" come from years of trial, errors, and feedback from others.
When I created the zCard project in Android Studio, I did through "New project with VCS". It was easier to just copy a link then paste it : Android Studio would do the rest.

I then realized my modifications (many are listed in the initial release), I published the project on GitHub, again, using Android Studio's integrated Git GUI. But I then saw that some files, like "FUNDING.md" have also been copied. I thought it was a mistake, since it contained data about funding your project, Catima. I found it odd, so I just decided to, as you said, _hard fork_.
GUI Git tends to be obscure regarding those aspects.

Finally, about the UI, I was actually going to either make a PR, or just contact you to discuss an improved UI. But I then saw that the screenshots in the README were updated. [The card's layout and style have been overhauled](https://github.com/CatimaLoyalty/Android/pull/1296), and I didn't open any PR, because you seemed like you were changing your design philosophy.

I consider the work put into Catima, and the years of contributions it took. I'm in my first year of high school, and I did my best to inform myself about how licenses work, for example. I understand the point you are making about the fork button and I'll consider this option when I have a little more free time.

Thanks for the constructiveness, and please forgive any grammatical errors or weird sentence construction.

**Comment by TheLastProject** [comment]
Thanks for your quick and detailed response, I understand things better now :)

I use the command line git myself so I'm not really experienced with the one inside Android Studio, but I think it would've worked better if you would've clicked "Fork" on the Catima GitHub page and then use the new GitHub repo it created (would've been github.com/ziadOUA/Catima in this case) as the URL for "New project with VCS". But no hard feelings, I understand the single commit better now :)

About the redesign, yeah, I guess we had bad timing there. I always found a lot of the parts of Catima a bit ugly but I have never been good with design so when someone showed up with a redesign I decided "yeah, this looks good, let's try it". It's complete now and the codebase is actually simpler because of it (it allowed me to delete a lot of old code), so I don't want to go back anymore, even though your changes made the old design also quite pretty.

It's really cool you can make such a clean design already in your first year of high school, I can't help but wonder how much further your designs could even improve with more experience, a cool future!

If you do find the time and feel like it, I would still love to see if some of the things you do for zCard can make it to Catima. Please feel free to submit PRs or create GitHub issues to discuss some of the changes you make at any time :)

**Comment by ziadOUA** [comment]
Hi ! @TheLastProject

I found the time to do it, and you were right, it is way easier to sync with Catima now (especially with the translations).
I also modified a bit the UI, while still considering the changes implemented since Catima 2.23.0.

Thanks.

**Comment by TheLastProject** [comment]
Cool :)

I don't personally prefer all your changes, but I do prefer some. I think it's great for user freedom to be able to choose between my idea of what's perfect and your idea. But I will pull in some of your commits where I agree it's an improvement if you don't mind :)

**Comment by ziadOUA** [comment]
Yes, of course ;)
