### ISSUE TITLE
Theme request

### ISSUE THREAD

**Issue by nvllz** [ziadOUA/zCard#18]
I don't like current themes. Even if you choose some blue theme color, some elements are colored in other way what makes it look less serious. I think some gray or black/white theme would compensate it. Something that would be consistent and color all elements in the shades of the chosen colors, which now works the other way and choosing magenta you get pink accents.. awful.

**Comment by ziadOUA** [comment]
Hello @nvllz,

The themes available in the app were generated using the material 3 "DynamicColors" library. This dynamic theming is part of the Material 3 update. Some element have a different color because (I'm assuming you are talking about the card that contains the barcode) I am using the tertiary color, contained in the theme.

I might create a black theme, but it won't play nice with the barcode.

**Comment by nvllz** [comment]
Tried to play with the screen layout, but couldn't build the app because of some errors and eventually gave it up. I think some dark gray in this place to accent the card box would make it look fine. Thanks for your reply!

**Comment by ziadOUA** [comment]
I fixed the errors, I will test some grey / black themes

**Comment by ziadOUA** [comment]
I added it, the app will be updated when I finish tying to fix the other issues you mentioned

**Comment by nvllz** [comment]
I like it! Could be a little darker for the black theme, but it's definitely the one I want to use. 
Thanks a lot ;)

**Comment by ziadOUA** [comment]
No problem :)
I try some darker variants
